import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

const TermsOfUse = () => {
  return (
    <>
        <Navbar />
        <div>
        Helicoprion est un genre éteint et fossile de poissons cartilagineux holocéphales de la famille des Helicoprionidae, qui ont vécu au Permien (296 à 254 Ma). Ils pouvaient mesurer jusqu'à 8–10 m de long et disposaient à la mâchoire inférieure d'une structure dentaire en spirale. Le nom du genre, construit sur le grec ἕλιξ / hélix (« spirale ») et πρίων / priôn (« scie »), signifie « scie en spirale ».La question prend un tour nouveau en 1966 avec la description d'un spécimen découvert en 1950 dans une mine de l'Idaho (États-Unis), dans lequel la spirale dentaire, de 23 cm de diamètre et portant 117 dents, est encore associée à des restes squelettiques cartilagineux au-dessus, en dessous et sur les côtés, en position naturelle3. En 2008 une étude sous la direction de Robert Purdy conclut à une position à l'arrière de la gorge1, mais elle soulève une polémique4,5. En 2013 une étude par microtomographie aux rayons X résout définitivement la question : elle identifie les restes cartilagineux comme la partie avant du palato-carré (appartenant à la mâchoire supérieure gauche) et le cartilage de Meckel (mâchoire inférieure gauche), place la spirale dentaire au niveau de la symphyse de la mâchoire inférieure et démontre qu'elle occupait toute la longueur des mandibules sans être proéminente. Le positionnement de la spirale implique un mouvement dorsal et postérieur des dents fonctionnelles lors de la fermeture de la gueule, tranchant les proies par cisaillement tout en les entraînant vers l'arrière3,2.Des dents d'Helicoprion ont été trouvés dans le monde entier : Norvège, Russie, Kazakhstan, Chine, Japon, Laos, Australie-Occidentale, Mexique, États-Unis (Idaho, Nevada, Wyoming, Texas, Utah et Californie) et Canada2 : ces poissons vivaient dans les mers chaudes qui bordaient la Pangée3. Plus de 50 % des fossiles attribués à Helicoprion sont des spécimens de H. davisii trouvés dans la formation Phosphoria (en) de l'Idaho ; 25 autres % ont été trouvés dans l'Oural (Russie), appartenant à l'espèce H. bessonowi2.On a émis l'hypothèse que ces prédateurs se nourrissaient d'ammonites et que leurs dents étaient adaptées à l'ouverture de la coquille de ces céphalopodes.

Une autre hypothèse est qu'ils nageaient dans les bancs de poissons en ouvrant la bouche, ce qui leur permettait d'attraper les poissons sur leurs nombreuses dents.La spirale dentaire pouvait atteindre 30 cm de diamètre et porter jusqu'à 160 dents. Comme chez les requins actuels, qui appartiennent à la même classe, de nouvelles dents poussaient périodiquement, mais contrairement à eux elles ne tombaient jamais : elles suivaient un mouvement circulaire, avec les plus anciennes (les plus petites) au centre de la spirale et les plus récentes (les plus grandes) à la périphérie3.

Histoire
Les premières reconstitutions ont supposé que la spirale dentaire était un organe denté préhensible, placé sur la mâchoire supérieure ou sur la mâchoire inférieure, ou bien même sur la nageoire dorsale ou sur la nageoire caudalea. La seconde de ces hypothèses, la plus classiquement adoptée, possédait deux variantes, selon qu'on plaçait la spirale dentaire à l'avant (au niveau de la symphyse mandibulaire) — la mâchoire inférieure étant alors supposée plus longue que la mâchoire supérieure — ou à l'arrière (au niveau de l'articulation temporo-mandibulaire)3.
        Helicoprion est un genre éteint et fossile de poissons cartilagineux holocéphales de la famille des Helicoprionidae, qui ont vécu au Permien (296 à 254 Ma). Ils pouvaient mesurer jusqu'à 8–10 m de long et disposaient à la mâchoire inférieure d'une structure dentaire en spirale. Le nom du genre, construit sur le grec ἕλιξ / hélix (« spirale ») et πρίων / priôn (« scie »), signifie « scie en spirale ».La question prend un tour nouveau en 1966 avec la description d'un spécimen découvert en 1950 dans une mine de l'Idaho (États-Unis), dans lequel la spirale dentaire, de 23 cm de diamètre et portant 117 dents, est encore associée à des restes squelettiques cartilagineux au-dessus, en dessous et sur les côtés, en position naturelle3. En 2008 une étude sous la direction de Robert Purdy conclut à une position à l'arrière de la gorge1, mais elle soulève une polémique4,5. En 2013 une étude par microtomographie aux rayons X résout définitivement la question : elle identifie les restes cartilagineux comme la partie avant du palato-carré (appartenant à la mâchoire supérieure gauche) et le cartilage de Meckel (mâchoire inférieure gauche), place la spirale dentaire au niveau de la symphyse de la mâchoire inférieure et démontre qu'elle occupait toute la longueur des mandibules sans être proéminente. Le positionnement de la spirale implique un mouvement dorsal et postérieur des dents fonctionnelles lors de la fermeture de la gueule, tranchant les proies par cisaillement tout en les entraînant vers l'arrière3,2.Des dents d'Helicoprion ont été trouvés dans le monde entier : Norvège, Russie, Kazakhstan, Chine, Japon, Laos, Australie-Occidentale, Mexique, États-Unis (Idaho, Nevada, Wyoming, Texas, Utah et Californie) et Canada2 : ces poissons vivaient dans les mers chaudes qui bordaient la Pangée3. Plus de 50 % des fossiles attribués à Helicoprion sont des spécimens de H. davisii trouvés dans la formation Phosphoria (en) de l'Idaho ; 25 autres % ont été trouvés dans l'Oural (Russie), appartenant à l'espèce H. bessonowi2.On a émis l'hypothèse que ces prédateurs se nourrissaient d'ammonites et que leurs dents étaient adaptées à l'ouverture de la coquille de ces céphalopodes.

                Une autre hypothèse est qu'ils nageaient dans les bancs de poissons en ouvrant la bouche, ce qui leur permettait d'attraper les poissons sur leurs nombreuses dents.La spirale dentaire pouvait atteindre 30 cm de diamètre et porter jusqu'à 160 dents. Comme chez les requins actuels, qui appartiennent à la même classe, de nouvelles dents poussaient périodiquement, mais contrairement à eux elles ne tombaient jamais : elles suivaient un mouvement circulaire, avec les plus anciennes (les plus petites) au centre de la spirale et les plus récentes (les plus grandes) à la périphérie3.

                Histoire
                Les premières reconstitutions ont supposé que la spirale dentaire était un organe denté préhensible, placé sur la mâchoire supérieure ou sur la mâchoire inférieure, ou bien même sur la nageoire dorsale ou sur la nageoire caudalea. La seconde de ces hypothèses, la plus classiquement adoptée, possédait deux variantes, selon qu'on plaçait la spirale dentaire à l'avant (au niveau de la symphyse mandibulaire) — la mâchoire inférieure étant alors supposée plus longue que la mâchoire supérieure — ou à l'arrière (au niveau de l'articulation temporo-mandibulaire)3.
                Helicoprion est un genre éteint et fossile de poissons cartilagineux holocéphales de la famille des Helicoprionidae, qui ont vécu au Permien (296 à 254 Ma). Ils pouvaient mesurer jusqu'à 8–10 m de long et disposaient à la mâchoire inférieure d'une structure dentaire en spirale. Le nom du genre, construit sur le grec ἕλιξ / hélix (« spirale ») et πρίων / priôn (« scie »), signifie « scie en spirale ».La question prend un tour nouveau en 1966 avec la description d'un spécimen découvert en 1950 dans une mine de l'Idaho (États-Unis), dans lequel la spirale dentaire, de 23 cm de diamètre et portant 117 dents, est encore associée à des restes squelettiques cartilagineux au-dessus, en dessous et sur les côtés, en position naturelle3. En 2008 une étude sous la direction de Robert Purdy conclut à une position à l'arrière de la gorge1, mais elle soulève une polémique4,5. En 2013 une étude par microtomographie aux rayons X résout définitivement la question : elle identifie les restes cartilagineux comme la partie avant du palato-carré (appartenant à la mâchoire supérieure gauche) et le cartilage de Meckel (mâchoire inférieure gauche), place la spirale dentaire au niveau de la symphyse de la mâchoire inférieure et démontre qu'elle occupait toute la longueur des mandibules sans être proéminente. Le positionnement de la spirale implique un mouvement dorsal et postérieur des dents fonctionnelles lors de la fermeture de la gueule, tranchant les proies par cisaillement tout en les entraînant vers l'arrière3,2.Des dents d'Helicoprion ont été trouvés dans le monde entier : Norvège, Russie, Kazakhstan, Chine, Japon, Laos, Australie-Occidentale, Mexique, États-Unis (Idaho, Nevada, Wyoming, Texas, Utah et Californie) et Canada2 : ces poissons vivaient dans les mers chaudes qui bordaient la Pangée3. Plus de 50 % des fossiles attribués à Helicoprion sont des spécimens de H. davisii trouvés dans la formation Phosphoria (en) de l'Idaho ; 25 autres % ont été trouvés dans l'Oural (Russie), appartenant à l'espèce H. bessonowi2.On a émis l'hypothèse que ces prédateurs se nourrissaient d'ammonites et que leurs dents étaient adaptées à l'ouverture de la coquille de ces céphalopodes.

                Une autre hypothèse est qu'ils nageaient dans les bancs de poissons en ouvrant la bouche, ce qui leur permettait d'attraper les poissons sur leurs nombreuses dents.La spirale dentaire pouvait atteindre 30 cm de diamètre et porter jusqu'à 160 dents. Comme chez les requins actuels, qui appartiennent à la même classe, de nouvelles dents poussaient périodiquement, mais contrairement à eux elles ne tombaient jamais : elles suivaient un mouvement circulaire, avec les plus anciennes (les plus petites) au centre de la spirale et les plus récentes (les plus grandes) à la périphérie3.

                Histoire
                Les premières reconstitutions ont supposé que la spirale dentaire était un organe denté préhensible, placé sur la mâchoire supérieure ou sur la mâchoire inférieure, ou bien même sur la nageoire dorsale ou sur la nageoire caudalea. La seconde de ces hypothèses, la plus classiquement adoptée, possédait deux variantes, selon qu'on plaçait la spirale dentaire à l'avant (au niveau de la symphyse mandibulaire) — la mâchoire inférieure étant alors supposée plus longue que la mâchoire supérieure — ou à l'arrière (au niveau de l'articulation temporo-mandibulaire)3.
        </div>
        <Footer />
    </>
  )
}

export default TermsOfUse